[build]
publish = "public"
command = "npm run build && npm run ipfs-deploy"

[context.production.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://cfzhous.netlify.com/*"
  to = "https://cfzhous.com/:splat"
  force = true
